name: SSH 连接  # 中文名字

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 9 */7 * *'  # 定时触发

jobs:
  connect:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码库  # 中文描述
        uses: actions/checkout@v3

      - name: 设置 Python  # 中文描述
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: 安装依赖  # 中文描述
        run: |
          python -m pip install --upgrade pip
          pip install paramiko
          pip install requests

      - name: 运行 SSH 连接脚本  # 中文描述
        env:
          ACCOUNTS: ${{ secrets.ACCOUNTS_JSON }}
        run: python ssh.py
